pincode_db = {
    "110001": {
        "pincode": "110001",
        "city": "New Delhi",
        "state": "Delhi",
        "district": "New Delhi",
    },
    "400001": {
        "pincode": "400001",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
    },
    "700001": {
        "pincode": "700001",
        "city": "Kolkata",
        "state": "West Bengal",
        "district": "Kolkata",
    },
    "600001": {
        "pincode": "600001",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "district": "Chennai",
    },
    "560001": {
        "pincode": "560001",
        "city": "Bangalore",
        "state": "Karnataka",
        "district": "Bangalore Urban",
    },
    "500001": {
        "pincode": "500001",
        "city": "Hyderabad",
        "state": "Telangana",
        "district": "Hyderabad",
    },
    "380001": {
        "pincode": "380001",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "district": "Ahmedabad",
    },
    "411001": {
        "pincode": "411001",
        "city": "Pune",
        "state": "Maharashtra",
        "district": "Pune",
    },
    "302001": {
        "pincode": "302001",
        "city": "Jaipur",
        "state": "Rajasthan",
        "district": "Jaipur",
    },
    "226001": {
        "pincode": "226001",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
    },
    "800001": {
        "pincode": "800001",
        "city": "Patna",
        "state": "Bihar",
        "district": "Patna",
    },
    "462001": {
        "pincode": "462001",
        "city": "Bhopal",
        "state": "Madhya Pradesh",
        "district": "Bhopal",
    },
    "160017": {
        "pincode": "160017",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "district": "Chandigarh",
    },
    "695001": {
        "pincode": "695001",
        "city": "Thiruvananthapuram",
        "state": "Kerala",
        "district": "Thiruvananthapuram",
    },
    "751001": {
        "pincode": "751001",
        "city": "Bhubaneswar",
        "state": "Odisha",
        "district": "Khordha",
    },
    "781001": {
        "pincode": "781001",
        "city": "Guwahati",
        "state": "Assam",
        "district": "Kamrup Metro",
    },
    "831001": {
        "pincode": "831001",
        "city": "Jamshedpur",
        "state": "Jharkhand",
        "district": "East Singhbhum",
    },
    "171001": {
        "pincode": "171001",
        "city": "Shimla",
        "state": "Himachal Pradesh",
        "district": "Shimla",
    },
    "190001": {
        "pincode": "190001",
        "city": "Srinagar",
        "state": "Jammu and Kashmir",
        "district": "Srinagar",
    },
    "303001": {
        "pincode": "303001",
        "city": "Ajmer",
        "state": "Rajasthan",
        "district": "Ajmer",
    },
    "248001": {
        "pincode": "248001",
        "city": "Dehradun",
        "state": "Uttarakhand",
        "district": "Dehradun",
    },
    "440001": {
        "pincode": "440001",
        "city": "Nagpur",
        "state": "Maharashtra",
        "district": "Nagpur",
    },
    "452001": {
        "pincode": "452001",
        "city": "Indore",
        "state": "Madhya Pradesh",
        "district": "Indore",
    },
    "641001": {
        "pincode": "641001",
        "city": "Coimbatore",
        "state": "Tamil Nadu",
        "district": "Coimbatore",
    },
    "395001": {
        "pincode": "395001",
        "city": "Surat",
        "state": "Gujarat",
        "district": "Surat",
    },
}
