[project]
name = "algo-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "gopaladhikari", email = "gopuadks@gmail.com" }]
requires-python = ">=3.14"
dependencies = ["yfinance>=1.7.0"]

[project.scripts]
start = "algo_bot.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
