[project]
name = "books-exchange"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "gopaladhikari", email = "gopuadks@gmail.com" }]
requires-python = ">=3.14"
dependencies = ["fastapi[standard]>=0.141.1", "sqlmodel>=0.0.39"]

[project.scripts]
books-exchange = "books_exchange:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "books_exchange.main:app"
