tea_menu = [
    {
        "id": 1,
        "name": "Masala Chai",
        "description": "Traditional black tea brewed with aromatic spices like cardamom, ginger, and cloves.",
        "category": "Milk Tea",
        "price": 20.00,
        "is_available": True,
    },
    {
        "id": 2,
        "name": "Ginger Chai",
        "description": "Strong milk tea infused with freshly crushed ginger to boost immunity.",
        "category": "Milk Tea",
        "price": 20.00,
        "is_available": True,
    },
    {
        "id": 3,
        "name": "Elaichi Chai",
        "description": "Classic milk tea fragrant with the sweet aroma of crushed green cardamom.",
        "category": "Milk Tea",
        "price": 20.00,
        "is_available": True,
    },
    {
        "id": 4,
        "name": "Cutting Chai",
        "description": "A half-glass of extra strong, highly boiled milk tea popular in Mumbai street stalls.",
        "category": "Milk Tea",
        "price": 12.00,
        "is_available": True,
    },
    {
        "id": 5,
        "name": "Kesar Chai",
        "description": "Rich and premium milk tea infused with pure saffron strands for a royal flavor.",
        "category": "Milk Tea",
        "price": 40.00,
        "is_available": True,
    },
    {
        "id": 6,
        "name": "Tandoori Chai",
        "description": "Smoky flavored tea prepared by pouring hot masala chai into a roasted clay kulhad.",
        "category": "Milk Tea",
        "price": 35.00,
        "is_available": False,
    },
    {
        "id": 7,
        "name": "Irani Chai",
        "description": "Slow-brewed black tea decoction mixed with thick, sweet, reduced milk cream.",
        "category": "Milk Tea",
        "price": 30.00,
        "is_available": True,
    },
    {
        "id": 8,
        "name": "Lemongrass Chai",
        "description": "Refreshing milk tea flavored with fresh lemongrass stalks.",
        "category": "Milk Tea",
        "price": 25.00,
        "is_available": True,
    },
    {
        "id": 9,
        "name": "Chocolate Chai",
        "description": "A delightful fusion of regular milk tea and sweet chocolate syrup.",
        "category": "Milk Tea",
        "price": 30.00,
        "is_available": True,
    },
    {
        "id": 10,
        "name": "Plain Black Tea",
        "description": "Pure Assam black tea brewed perfectly without any milk or sugar.",
        "category": "Black Tea",
        "price": 15.00,
        "is_available": True,
    },
    {
        "id": 11,
        "name": "Lemon Tea",
        "description": "Light black tea mixed with fresh lemon juice and a hint of rock salt.",
        "category": "Black Tea",
        "price": 18.00,
        "is_available": True,
    },
    {
        "id": 12,
        "name": "Honey Lemon Ginger Tea",
        "description": "Soothe-your-throat blend of black tea, ginger extract, lemon juice, and pure honey.",
        "category": "Black Tea",
        "price": 30.00,
        "is_available": True,
    },
    {
        "id": 13,
        "name": "Sulaimani Tea",
        "description": "Spiced black tea with lemon and mint, popular in the Malabar region.",
        "category": "Black Tea",
        "price": 25.00,
        "is_available": True,
    },
    {
        "id": 14,
        "name": "Classic Green Tea",
        "description": "Steeped premium green tea leaves, rich in antioxidants with a earthy taste.",
        "category": "Green Tea",
        "price": 25.00,
        "is_available": True,
    },
    {
        "id": 15,
        "name": "Mint Green Tea",
        "description": "Refreshing green tea brewed with fresh garden mint leaves.",
        "category": "Green Tea",
        "price": 30.00,
        "is_available": True,
    },
    {
        "id": 16,
        "name": "Tulsi Green Tea",
        "description": "Healthy green tea infused with holy basil leaves for stress relief.",
        "category": "Green Tea",
        "price": 30.00,
        "is_available": True,
    },
    {
        "id": 17,
        "name": "Jasmine Green Tea",
        "description": "Lightly scented green tea leaves layered with delicate jasmine blossoms.",
        "category": "Green Tea",
        "price": 35.00,
        "is_available": False,
    },
    {
        "id": 18,
        "name": "Chamomile Tea",
        "description": "Caffeine-free herbal infusion made from dried chamomile flowers to aid sleep.",
        "category": "Herbal Tea",
        "price": 40.00,
        "is_available": True,
    },
    {
        "id": 19,
        "name": "Hibiscus Tea",
        "description": "Tart and tangy herbal tea brewed from deep red hibiscus petals.",
        "category": "Herbal Tea",
        "price": 40.00,
        "is_available": True,
    },
    {
        "id": 20,
        "name": "Kahwa",
        "description": "Kashmiri green tea brewed with saffron, cinnamon, cardamom, and chopped almonds.",
        "category": "Specialty Tea",
        "price": 50.00,
        "is_available": True,
    },
    {
        "id": 21,
        "name": "Butter Tea",
        "description": "Traditional Himalayan tea made from tea leaves, yak butter, water, and salt.",
        "category": "Specialty Tea",
        "price": 45.00,
        "is_available": False,
    },
    {
        "id": 22,
        "name": "Classic Iced Tea",
        "description": "Chilled black tea served over ice cubes with a slice of fresh lemon.",
        "category": "Iced Tea",
        "price": 35.00,
        "is_available": True,
    },
    {
        "id": 23,
        "name": "Peach Iced Tea",
        "description": "Sweet and refreshing cold black tea infused with natural peach flavor.",
        "category": "Iced Tea",
        "price": 45.00,
        "is_available": True,
    },
    {
        "id": 24,
        "name": "Blueberry Iced Tea",
        "description": "Vibrant iced tea blended with sweet blueberry puree and mint.",
        "category": "Iced Tea",
        "price": 50.00,
        "is_available": True,
    },
    {
        "id": 25,
        "name": "Matcha Iced Latte",
        "description": "Chilled, whisked Japanese green tea powder served over cold milk and ice.",
        "category": "Iced Tea",
        "price": 65.00,
        "is_available": True,
    },
]
