SELECT * FROM Users;

ALTER TABLE users ADD COLUMN is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE users DROP COLUMN is_active;

ALTER TABLE users MODIFY username VARCHAR(50);

ALTER TABLE users MODIFY COLUMN email VARCHAR(30) AFTER id;

ALTER TABLE users MODIFY COLUMN date_of_birth VARCHAR(30) FIRST;

SELECT * FROM Users;